
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://belenmwtnercbjdxbnqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlbGVubXd0bmVyY2JqZHhibnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDM3NjUsImV4cCI6MjA2NjI3OTc2NX0.Eyg3ePtRoY-OlsB-AAGp0cna50yRQlXshzg_nq9zyi8";

console.log('Supabase client initializing with URL:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Test connection
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    console.error('Supabase connection test failed:', error);
  } else {
    console.log('Supabase connection test successful');
  }
}).catch(error => {
  console.error('Supabase connection exception:', error);
});
